version: '3'

services:
  pydio:
    image: wilply/pydio_cells
    container_name: pydio
    ports:
      - 8080:8080
    links:
      - pydio_db
    volumes:
      - /cells/.config/pydio/cells
    environment:
      - SSL=0
      - RUN_AS_ROOT=0
      - PUID=1500
      - PGID=1500
      - CELLS_BIND=:8080
      - CELLS_EXTERNAL=http://cells.example.com:8080

  pydio_db:
    image: mariadb
    container_name: pydio_db
    restart: always
    volumes:
      - /var/lib/mysql
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=cells
      - MYSQL_USERNAME=pydio
      - MYSQL_PASSWORD=pydiopwd
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]