version: '3'

services:
  pydio:
    image: cells:dev
    container_name: pydio
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    links:
      - pydio_db
    volumes:
      - /mnt/ETC/DOCKER/container_files/09_pydio/pydio:/root/.config/pydio/cells
      - /mnt/DATA:/mnt/DATA
    environment:
      - SSL=0
      - CELLS_BIND=localhost:8080
      - CELLS_EXTERNAL=http://cells.wilply.fr:8080
      - PUID=1500
      - PGID=1500

  pydio_db:
    image: mariadb
    container_name: pydio_db
    restart: always
    volumes:
      - /mnt/ETC/DOCKER/container_files/09_pydio/pydio_db/mysql:/var/lib/mysql
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=cells
      - MYSQL_USERNAME=pydio
      - MYSQL_PASSWORD=pydiopwd
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]